version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clock_it_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ENVIRONMENT=development
      - DEBUG=True
      - RUN_MIGRATIONS=false
    env_file:
      - .env
    restart: unless-stopped
